import { TypeID } from 'typeid-js';
import { v7 as uuidv7, validate as uuidValidate, version as uuidVersion } from 'uuid';

/**
 * Identifier strategy (ADR-0013):
 *  - entity and version ids are UUIDv7, generated by the application;
 *  - canonical hashed payloads always carry the plain lowercase UUID string;
 *  - APIs present ids as TypeIDs (`<prefix>_<base32>`), a presentation concern only;
 *  - content hashes are `sha256:<64 lowercase hex>` (see @br/canonical);
 *  - blockchain references are never identities.
 */
declare const uuidBrand: unique symbol;
export type Uuid = string & { readonly [uuidBrand]: true };

const CANONICAL_UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

export function newId(): Uuid {
  return uuidv7() as Uuid;
}

/** Accepts only canonical lowercase UUIDs (any RFC 9562 version); use `parseUuid` for input. */
export function isUuid(value: string): value is Uuid {
  return CANONICAL_UUID.test(value) && uuidValidate(value);
}

export function isUuidV7(value: string): value is Uuid {
  return isUuid(value) && uuidVersion(value) === 7;
}

/** Parses external input: uppercase is lowercased; any other form is rejected. */
export function parseUuid(value: string): Uuid {
  const lower = value.toLowerCase();
  if (!isUuid(lower)) throw new TypeError(`not a canonical UUID: ${JSON.stringify(value)}`);
  return lower;
}

/** TypeID prefixes used in API presentation. Never used inside hashed content. */
export const IdPrefix = {
  principal: 'prin',
  principalKey: 'pkey',
  trustAnchor: 'anchor',
  authorityGrant: 'grant',
  result: 'result',
  resultVersion: 'rv',
  ledgerEntry: 'le',
  domainEvent: 'evt',
} as const;
export type IdPrefix = (typeof IdPrefix)[keyof typeof IdPrefix];

export function toTypeId(prefix: IdPrefix, id: Uuid): string {
  return TypeID.fromUUID(prefix, id).toString();
}

export function fromTypeId(expectedPrefix: IdPrefix, typeId: string): Uuid {
  const parsed = TypeID.fromString(typeId);
  if (parsed.getType() !== expectedPrefix) {
    throw new TypeError(`expected TypeID prefix ${expectedPrefix}, got ${parsed.getType()}`);
  }
  return parseUuid(parsed.toUUID());
}
