import type { CanonicalFactKind } from '@br/domain';

/**
 * Bounded trace reason codes (pattern ^[A-Z][A-Z0-9_]{0,63}$). Authority denials reuse the BRT-03
 * AuthorizationReason vocabulary verbatim (NO_GRANT_FOR_CAPABILITY, SCOPE_NOT_COVERED,
 * GRANT_NOT_VALID_AT_TIME, GRANT_REVOKED, ANCHOR_*, CONFLICT_OF_INTEREST, CONFLICT_CHECK_UNAVAILABLE…).
 */
export const Reason = {
  // V0
  CLAIM_HASH_BOUND: 'CLAIM_HASH_BOUND',
  SUBMITTER_KNOWN: 'SUBMITTER_KNOWN',
  SUBMITTER_UNKNOWN: 'SUBMITTER_UNKNOWN',
  // signed facts / key trust (signature validity ≠ key trust ≠ authority)
  RETRACTED: 'RETRACTED',
  SUPERSEDED: 'SUPERSEDED',
  KEY_UNKNOWN: 'KEY_UNKNOWN',
  KEY_NOT_OWNED: 'KEY_NOT_OWNED',
  KEY_NOT_VALID_AT_ISSUANCE: 'KEY_NOT_VALID_AT_ISSUANCE',
  KEY_REVOKED: 'KEY_REVOKED',
  KEY_COMPROMISED: 'KEY_COMPROMISED',
  // issuer independence (V1)
  SUBMITTER_SELF: 'SUBMITTER_SELF',
  SAME_SIDE_AS_SUBMITTER: 'SAME_SIDE_AS_SUBMITTER',
  COUNTERPARTY: 'COUNTERPARTY',
  /** BRT-01 V1 registered official (structural REGISTERED_OFFICIAL fact; not authority). */
  REGISTERED_OFFICIAL: 'REGISTERED_OFFICIAL',
  NOT_REGISTERED_OFFICIAL: 'NOT_REGISTERED_OFFICIAL',
  REGISTERED_OFFICIAL_CONFLICTED: 'REGISTERED_OFFICIAL_CONFLICTED',
  COUNTERPARTY_PATH_EVALUATED: 'COUNTERPARTY_PATH_EVALUATED',
  REGISTERED_OFFICIAL_PATH_EVALUATED: 'REGISTERED_OFFICIAL_PATH_EVALUATED',
  NO_STANDING: 'NO_STANDING',
  RELATION_TIME_UNDETERMINED: 'RELATION_TIME_UNDETERMINED',
  PARTICIPATION_UNKNOWN: 'PARTICIPATION_UNKNOWN',
  SUBMITTER_SIDE_UNKNOWN: 'SUBMITTER_SIDE_UNKNOWN',
  MINIMUM_MET: 'MINIMUM_MET',
  BELOW_MINIMUM: 'BELOW_MINIMUM',
  // contradictions
  COUNTERPARTY_DENY: 'COUNTERPARTY_DENY',
  SUBMITTER_DENY: 'SUBMITTER_DENY',
  COUNTERPARTY_DENY_PRESENT: 'COUNTERPARTY_DENY_PRESENT',
  COUNTERPARTY_DENY_OUTRANKED_BY_CERTIFICATION: 'COUNTERPARTY_DENY_OUTRANKED_BY_CERTIFICATION',
  V2_OFFICIAL_DECLARATION_PASSED: 'V2_OFFICIAL_DECLARATION_PASSED',
  V2_NO_AUTHORIZED_DENY_PASSED: 'V2_NO_AUTHORIZED_DENY_PASSED',
  V2_CERTIFICATION_EXCEPTION_NOT_MET: 'V2_CERTIFICATION_EXCEPTION_NOT_MET',
  NO_COUNTERPARTY_DENY: 'NO_COUNTERPARTY_DENY',
  AUTHORIZED_DENY: 'AUTHORIZED_DENY',
  DENY_AUTHORITY_UNKNOWN: 'DENY_AUTHORITY_UNKNOWN',
  NO_AUTHORIZED_DENY: 'NO_AUTHORIZED_DENY',
  ACTIVE_DISPUTE_CLAIM: 'ACTIVE_DISPUTE_CLAIM',
  NO_ACTIVE_DISPUTE_CLAIM: 'NO_ACTIVE_DISPUTE_CLAIM',
  // evidence
  NO_PRIMARY_TYPES_DECLARED: 'NO_PRIMARY_TYPES_DECLARED',
  TYPE_NOT_PRIMARY: 'TYPE_NOT_PRIMARY',
  EVIDENCE_UNAVAILABLE: 'EVIDENCE_UNAVAILABLE',
  AI_ONLY_EVIDENCE: 'AI_ONLY_EVIDENCE',
  GENERIC_MACHINE_DERIVED: 'GENERIC_MACHINE_DERIVED',
  INVALIDATING_ASSESSMENT: 'INVALIDATING_ASSESSMENT',
  NO_INVALIDATING_ASSESSMENT: 'NO_INVALIDATING_ASSESSMENT',
  INTEGRITY_VERIFIED: 'INTEGRITY_VERIFIED',
  SOURCE_SIGNATURE_NOT_APPLICABLE: 'SOURCE_SIGNATURE_NOT_APPLICABLE',
  NO_PRIMARY_EVIDENCE: 'NO_PRIMARY_EVIDENCE',
  UNKNOWN_PROVENANCE: 'UNKNOWN_PROVENANCE',
  INDEPENDENT_SOURCE: 'INDEPENDENT_SOURCE',
  // official declaration / certification (V2)
  OFFICIAL_DECLARATION_AUTHORIZED: 'OFFICIAL_DECLARATION_AUTHORIZED',
  T5_DECLARATION_AUTHORIZED: 'T5_DECLARATION_AUTHORIZED',
  AUTHORIZED_RESULT_ACCURATE_PRESENT: 'AUTHORIZED_RESULT_ACCURATE_PRESENT',
  NO_AUTHORIZED_DECLARATION: 'NO_AUTHORIZED_DECLARATION',
  // sanction / recognition (V3)
  SANCTION_AUTHORIZED: 'SANCTION_AUTHORIZED',
  SANCTION_DENIED: 'SANCTION_DENIED',
  NO_AUTHORIZED_SANCTION: 'NO_AUTHORIZED_SANCTION',
  RECOGNITION_TOO_LOW: 'RECOGNITION_TOO_LOW',
  RECOGNITION_PLATFORM_CEILING: 'RECOGNITION_PLATFORM_CEILING',
  CERTIFICATION_ROOTED: 'CERTIFICATION_ROOTED',
  CERTIFICATION_NOT_ROOTED: 'CERTIFICATION_NOT_ROOTED',
  PREREQUISITE_NOT_MET: 'PREREQUISITE_NOT_MET',
  OFFICIAL_EVIDENCE_SET_UNDECLARED: 'OFFICIAL_EVIDENCE_SET_UNDECLARED',
  OFFICIAL_EVIDENCE_TYPE_MISSING: 'OFFICIAL_EVIDENCE_TYPE_MISSING',
  OFFICIAL_EVIDENCE_SET_COMPLETE: 'OFFICIAL_EVIDENCE_SET_COMPLETE',
  IDENTITY_CONFIRMED: 'IDENTITY_CONFIRMED',
  IDENTITY_NOT_CONFIRMED: 'IDENTITY_NOT_CONFIRMED',
  // conditions / ratification (V4)
  RECORD_CATEGORY_UNDECLARED: 'RECORD_CATEGORY_UNDECLARED',
  CONDITIONS_AUTHORIZED: 'CONDITIONS_AUTHORIZED',
  CONDITIONS_DENIED: 'CONDITIONS_DENIED',
  CONDITION_ASPECT_MISSING: 'CONDITION_ASPECT_MISSING',
  PLATFORM_WITNESSED_SIGNATURE: 'PLATFORM_WITNESSED_SIGNATURE',
  ALL_SIGNATURES_NON_WITNESSED: 'ALL_SIGNATURES_NON_WITNESSED',
  RATIFIER_NOT_HUMAN: 'RATIFIER_NOT_HUMAN',
  RATIFICATION_AUTHORIZED: 'RATIFICATION_AUTHORIZED',
  NO_AUTHORIZED_RATIFICATION: 'NO_AUTHORIZED_RATIFICATION',
  // structure
  DERIVED_INPUTS_REQUIRED: 'DERIVED_INPUTS_REQUIRED',
  NOT_A_CLASSIFICATION: 'NOT_A_CLASSIFICATION',
} as const;
export type Reason = (typeof Reason)[keyof typeof Reason];

/** "NOT_SUPPORTED_<KIND>": the fact kind has no canonical producer for this snapshot. */
export function notSupported(kind: CanonicalFactKind): string {
  return `NOT_SUPPORTED_${kind}`;
}
